### PR TITLE
py3k and  use latest owslib

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR implements:

- `Python 2.7` and `+3.4` compatibility;
- latest `owslib` syntax;
- pinning only of `lxml` due to some suspicious test breakages.

The `Python 3` code is untested due to the use of `lettuce`, which is Python 2 only. Note that both `lettuce` and `nose` are dead projects and I strongly recommend adapting the tests to [`pytest-bdd`](https://github.com/pytest-dev/pytest-bdd) and `pytest` instead.

There are [some errors](https://travis-ci.org/ocefpaf/pyGDP/jobs/264961036) when I unpin `lxml` that I will investigate and fix in another PR. (Pinning to such an old `lxml` is not recommended.)

There are some noise due to white spaces and indentation fixes. If those are  a nuisance I can revert them.

Ping @rsignell-usgs who requested `PyGDP` on Python 3.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@ocefpaf, wow, that's a lot of progress!  Fantastic!   

The notebook I'm trying to run that uses pyGDP got pretty far with this PR:
https://gist.github.com/anonymous/73a433f1772b0642b3bffdfc3e9f513d
but from `TypeError: must be str, not bytes`, it looks like there still might be a typeError left?

**Comment by dblodgett-usgs** [comment]
Thanks @ocefpaf 

We've been talking about a revamping pyGDP on a couple other fronts. @pnorton-usgs has been doing some work on the process monitoring code and some other things. Maybe he'll be able to review / help incorporate some of this into his future work?

**Comment by ocefpaf** [comment]
@rsignell-usgs I don't believe that failure is related to `pyGDP`. It looks like a bug in `OWSLib`.
See https://github.com/geopython/OWSLib/pull/380 for a possible fix.

With the OWSLib patch I can get further on your notebook. See http://nbviewer.jupyter.org/gist/ocefpaf/28e060193c6b1ee764ef6dff325c85da

The problem there is that you seems to expect an URL while pyGDP is returning a file name in the current path.

@dblodgett-usgs what is the expected behavior `submitFeatureWeightedGridStatistics` in that case?

**Comment by dblodgett-usgs** [comment]
The expected behavior is a file. I think this notebook uses a very old version of pyGDP that returned a URL to download the file. See this call: https://github.com/USGS-CIDA/pyGDP/blob/master/pygdp/_execute_request.py#L44

**Comment by dblodgett-usgs** [comment]
@ocefpaf looking over this, I'd like to go ahead and merge, but I think a few things in the README regarding install should change based on these changes? I'm not much of a python developer so am not sure exactly what the best guidance should be now that python 3 and latest version of some packages work.

Would you be willing to add a bit of an update to the README?

**Comment by ocefpaf** [comment]
> Would you be willing to add a bit of an update to the README?

I can take a look but there are more things that I would like to change here before tackling the README, like the `setup.py` and some install details.

I would prefer to keep the PRs small and self-contained. So if you are OK with this one let us merge it and I'll send a new one right after that.

Note that the code is not fully tested on Python 3 b/c the testing framework does not work on Python 3! So any new release should have warning. (We only tested @rsignell-usgs' notebook.)

We also need https://github.com/geopython/OWSLib/pull/380, which may take a while...

**Comment by dblodgett-usgs** [comment]
Alright. Yeah, sounds good. Thank you for helping us out on this!!

**Pull request merged**
