### PR TITLE
added .travis.yml

### PR DESCRIPTION
**Pull request by ayan-usgs**

### CODE REVIEW

**Comment by jread-usgs** [comment]
@ayan-usgs need me to add this to our travis account, or do you have that covered?

**Comment by ayan-usgs** [comment]
@dblodgett-usgs  and @jread-usgs,

Getting the tests running on my fork was very straightforward. Do either of you have admin rights on USGS-CIDA/pyGDP to enable the service? I don't have admin rights on this repo.

**Comment by jread-usgs** [comment]
I don't @davidmsibley or @isuftin have the cabinet locked down.

**Comment by ayan-usgs** [comment]
Also, there are four failing tests when I initially cloned this repo. Not sure how long they've been failing though.

```
List of failed scenarios:
  @not_working
  Scenario: Running a sample in Rhode Island         # \Lettuce_Tests\features\Test_Feature_Categorical_Grid_Coverage.feature:7
  @not_working
  Scenario: Submit Feature Coverage WCS Intersection               # \Lettuce_Tests\features\Test_Feature_Coverage_WCS_Inersection.feature:7
  @not_working
  Scenario: Submit FWGS without time                         # \Lettuce_Tests\features\Test_Feature_Weighted_Grid_Statistics.feature:30
  @not_working
  Scenario: Submit FWGS with Arc Shapefile                   # \Lettuce_Tests\features\Test_Feature_Weighted_Grid_Statistics.feature:38
```

**Comment by ayan-usgs** [comment]
The test failures seem to be due to a remote process failing.

**Comment by jread-usgs** [comment]
kicking a build off here https://travis-ci.org/USGS-R/geoknife to see if it sees the same issue. GDP is in refactor-zone right now, but I didn't think it made it to prod.

**Comment by ayan-usgs** [comment]
@davidmsibley has added the webhook.

**Comment by ayan-usgs** [comment]
@dblodgett-usgs,

Have you tried running the tests with Python 3? I found that Lettuce will not work with Python 3.  There is incompatible grammar in it's __init__.py that causes tests to vomit. The changes in Python 3 are described at https://www.python.org/dev/peps/pep-3110/. I have opted to not test Python 3 for the time being.

**Comment by dblodgett-usgs** [comment]
No, We've never tried this on python 3. I'd avoid it.

**Comment by jread-usgs** [comment]
Ok, I was able to kick off the build by adding another PR that started after the travis repo was switched on by sibley. I will kill that PR as this one is building too.

**Comment by jread-usgs** [comment]
Build is failing, but it looks like travis is set up properly. I am merging this and will point the test results to @dblodgett-usgs https://travis-ci.org/USGS-CIDA/pyGDP/builds/58754585

**Pull request closed without merging**
