### PR TITLE
Support version 0.9.x of OWSLib

### PR DESCRIPTION
**Pull request by ayan-usgs**
Changes to support current versions of OWSLib. 

During this work a bug was found in version 0.9.1 of OWSLib; the bug has since been fixed, but a new version hasn't been released. Requirements reflect this with the caveat that there isn't a released version over 0.9.1 right now. I'd recommend merging these changes into master (or another branch) and cut a release when a new version of OWSLib is available.

### CODE REVIEW

**Comment by dblodgett-usgs** [comment]
@ayan-usgs I'm seeing 0.9.1 here... https://github.com/geopython/OWSLib/releases what isn't released about it yet?

**Comment by ayan-usgs** [comment]
@dblodgett-usgs,

@rsignell-usgs wanted pyGDP working with version 0.9.1, but the was a bug which was fixed with this commit: https://github.com/geopython/OWSLib/commit/30e6d399885c861bd23e3360dcfd34d0c74dc75e. The commit came six days after 0.9.1 was released.

**Comment by dblodgett-usgs** [comment]
@ayan-usgs Looks like 0.9.2 is released. Can you update the requirements in this pull request? Go ahead and merge once the tests all pass.

Thanks for taking care of this!

**Comment by ayan-usgs** [comment]
Hmm... only one test failure. I'll take a look at it and proceed from there.

**Comment by ayan-usgs** [comment]
All happy. :smile:

**Comment by ayan-usgs** [comment]
@dblodgett-usgs,

Merged. I suspect @rsignell-usgs will want a new release of pyGDP as well. Would you like to take care of that or should I?

**Comment by rsignell-usgs** [comment]
maybe let me try my dustbowl workflow first?

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

Sure. pyGDP-master should be good to go.

**Comment by dblodgett-usgs** [comment]
Pending @rsignell-usgs tests, if you have a second to do it, go ahead and build the release @ayan-usgs

**Comment by rsignell-usgs** [comment]
Okay, I tried my Dustbowl Notebook, and everything worked.  Hurrah!!!!!!

Thanks Guys!    Cut the release!

**Comment by ayan-usgs** [comment]
@rsignell-usgs 

Cool beans.

**Comment by rsignell-usgs** [comment]
Is this debug stuff supposed to be turned on by default?
clipboard01

**Comment by ayan-usgs** [comment]
@rsignell-usgs,

I'm going to say: no, they shouldn't be there.

**Pull request merged**
